# --- VDN specific parameters ---

# use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 100000 # 500000 for 6h_vs_8z

runner: "parallel"
batch_size_run: 8
buffer_size: 5000
batch_size: 128

t_max: 10050000

# update the target network every {} episodes
target_update_interval: 200

# use the Q_Learner to train
mac: "wm_mac"
agent: "wm_hyper_rnn"
hpn_hyper_dim: 64
agent_output_type: q

learner: "wm_learner"
mixer: "wm_qmix"
mixing_embed_dim: 32
hypernet_embed: 64
lr: 0.001 # Learning rate for agents
td_lambda: 0.6
optimizer: 'adam'
q_lambda: False

obs_rl_lambda: 10
state_rl_lambda: 100
latent_rl_lambda: 10

#name: "vdn_env=8_adam_td_lambda"
name: "world_model_hyper_qmix_v1"

obs_agent_id: True # Include the agent's one_hot id in the observation
obs_last_action: False # Include the agent's last action (one_hot) in the observation